[package]
name = "dpdk-gpu-test"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capsule = { path = "capsule/core/", features = [] }
rustacuda = "0.1.2"
rustacuda_core = "0.1.2"
page_size = "0.4.2"
# tracing = { version = "0.1.17", features = ["log", "log-always"] }
# simple_logger = "1.6.0"
